/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface": "#dde4e5",
        "background": "#0e1416",
        "surface": "#0e1416",
        "surface-container-lowest": "#090f11",
        "surface-container-low": "#161d1e",
        "surface-container": "#1a2122",
        "surface-container-high": "#242b2d",
        "surface-container-highest": "#2f3638",
        "surface-bright": "#343a3c",
        "surface-variant": "#2f3638",
        "surface-dim": "#0e1416",
        "on-surface-variant": "#bbc9cd",
        "outline": "#859397",
        "outline-variant": "#3c494c",
        "primary": "#8aebff",
        "primary-container": "#22d3ee",
        "primary-fixed": "#a2eeff",
        "primary-fixed-dim": "#2fd9f4",
        "on-primary": "#00363e",
        "on-primary-fixed": "#001f25",
        "on-primary-container": "#005763",
        "secondary": "#adc8f5",
        "secondary-container": "#2f4a70",
        "secondary-fixed": "#d5e3ff",
        "secondary-fixed-dim": "#adc8f5",
        "on-secondary": "#133155",
        "on-secondary-fixed": "#001c3b",
        "on-secondary-container": "#9fbae6",
        "tertiary": "#ffd6a3",
        "tertiary-container": "#ffb13b",
        "tertiary-fixed": "#ffddb5",
        "tertiary-fixed-dim": "#ffb957",
        "on-tertiary": "#462b00",
        "on-tertiary-fixed": "#2a1800",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#dde4e5",
        "inverse-on-surface": "#2b3233",
        "inverse-primary": "#006877",
        "surface-tint": "#2fd9f4",
        "on-background": "#dde4e5",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-safe": "24px",
        "panel-padding": "16px",
        "grid-gap": "1px",
      },
      fontFamily: {
        "mono-data": ["JetBrains Mono", "monospace"],
        "headline-md": ["Space Mono", "monospace"],
        "headline-lg": ["Space Mono", "monospace"],
        "display-tactical": ["Space Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "mono-data": ["14px", { lineHeight: "1.4", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "700" }],
        "display-tactical": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
