global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "batalhanaval-api"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s
    scheme: https
    static_configs:
      - targets: ["batalhanaval-te2c.onrender.com"]
        labels:
          application: "batalhanaval-api"
          environment: "production"
