export const ORIENTATIONS = { HORIZONTAL: 'HORIZONTAL', VERTICAL: 'VERTICAL' };

export const GAME_STATUS = {
  WAITING: 'WAITING',
  PLACING: 'PLACING',
  IN_PROGRESS: 'IN_PROGRESS',
  FINISHED: 'FINISHED',
  CANCELLED: 'CANCELLED',
};

export const SHOT_RESULT = { MISS: 'MISS', HIT: 'HIT', SUNK: 'SUNK' };
